### ISSUE TITLE
TODO list after merging Christoph's branch

### ISSUE THREAD

**Issue by norihiro-w** [ufz/ogs#1167]
Sorted by priority

(1) Code modularity
- [x] fix circular dependency #1200 (PR #1208)
- [ ] split FileIO #1164 (PR #1182 #1202 #1216 #1217 #1225)

(2) Better interface in core modules
- [x] remove #ifdef USE_EIGEN. (DenseMatrix will be replaced later by Tom) (PR #1218)
- [x] remove unused Sparse stuff in MathLib/LinAlg (PR #1219)
- [x] consistent function names, e.g. getN and getNum #1220 (PR #1243)
- [ ] make GeoLib related stuff in MeshLib to MeshGeoToolsLib into MeshLib #1215 (PR #1242 and more )
- [x] Error handling: Replace `std::abort()` with `exception` #1165 (PR #1245)
- [ ] Cleanup mat/vec interfaces (see also #1077). Currently algebraic operations are given in both BLAS namespace and in mat/vec classes, which is confusing users. The functions should be gathered in one place, either as class functions or in BLAS namesake (The name BLAS is confusing and should be renamed). (PR #1247 and more)

(3) Cleanup for faster compiling, etc.
- [x] Global typedef for sparse matrix and vectors #1134
- [ ] Minimize usage of template techniques for better developer friendly API and shorter compiling time (To be specified. Removing some templates is already given above. ) #1137
- [ ] Customize selection of libraries in cmake #1142
- [ ] rename `NumLib/ODESolver` to `NumLib/TimeIntegration`.
- [ ] clean up includes. @endJunction has some fancy tool for it. Maybe by that we already gain some compilation speed (at least if not building from scratch).

(4) Essential feature addition / deletion 
- [ ] Data output for each mesh, not for each process (I guess this influences the process interface)
- [ ] Global typedef for integer and real, e.g. `OgsInt`, `OgsReal`. This is necessary for supporting `long long` (e.g. more than 2 billion DoFs (e.g. 20 million HEX27 elements for mechanics in 3D) ) and quad precision, which are also supported by PETSc, Lis, and PARDISO.
- [ ] Introducing Parameters class (I am thinking something like TCLAP but parsing ConfigTree). This enables us to include documentation of parameters into the executable (and force developers to write short documentation for each parameter) so that we can print help of all parameters with `ogs --help-parameters`.

(5) Misc. feature addition / deletion
- [ ] add connectivity info to a DoF table. Currently we need to use both a mesh and a DoF table to get the information.
- [ ] Fix or delete Crank-Nicolson #1148
- [ ] OpenMP for assembly #1163

**Comment by chleh** [comment]
* [ ] rename `NumLib/ODESolver` to `NumLib/TimeIntegration`.
* [ ] For the cleanup of matrix/vector interfaces I'd like to bring forward #1077.

I'm curious to see what changes the use of PETSc nonlinear solvers and timesteppers will demand.

**Comment by chleh** [comment]
* [ ] clean up includes. @endJunction has some fancy tool for it. Maybe by that we already gain some compilation speed (at least if not building from scratch).

**Comment by norihiro-w** [comment]
@chleh I merged your TODOs

**Comment by norihiro-w** [comment]
update: sorted by priority

**Comment by norihiro-w** [comment]
I checked signed integer type again. see below. maybe that was a Windows server I tested before. Anyway IMO following C++ standard is the best practice as other libraries did.

Byte length vs value ranges:

bytes | min | max
--------|------|-------
 4 | −2,147,483,648 | 2,147,483,647
 8 | −9,223,372,036,854,775,808 | 9,223,372,036,854,775,807

Integer types vs Byte length:

type | C++ standard | Win32 | Win64 | *nix 
------|--------------------|-----------|----------|---------
int | min. 2 bytes | 4 bytes | 4 bytes | 4 bytes 
long | min. 4 bytes | 4 bytes | 4 bytes | 8 bytes 
long long | min. 8 bytes | 8 bytes | 8 bytes | 8 bytes

**Comment by chleh** [comment]
When changing the integer types, maybe we should use one of those: http://en.cppreference.com/w/cpp/header/cstdint.
Or we stick to the defaults defined in LIS/PETSc/Eigen.

**Comment by norihiro-w** [comment]
I close this TODO list and will not make further cleanup except for current PRs because the planned period (1 month) is over. 

TODOs in Point 1 and 2 were successfully done. Thanks all for your support and patience for the drastic changes.

**Comment by ogsbot** [comment]
OpenGeoSys development has been moved to [GitLab](https://gitlab.opengeosys.org/ogs/ogs).

[See this issue on GitLab](https://gitlab.opengeosys.org/ogs/ogs/-/issues/1167).
