### ISSUE TITLE
Todo August

### ISSUE THREAD

**Issue by endJunction** [ufz/ogs#1350]
(Unordered) list of ideas (old and new) floating around; Add new ideas/reorder items/comment it!
## PRs or ready for PR
- [x] Thermal conduction process (@grubbymoon) #1328 
- [x] Numerical Jacobian assembly. Cf. #1338 and #1352. @chleh
- [x] finish time integration unit tests. @chleh (after numerical Jacobian, #1381)
- [ ] Fix or delete Crank-Nicolson #1148 @chleh, ~~fixing it~~ unfixable with the current interface. Going to delete it. Ready for PR. (I'd rather keep it (renamed) if the tests are good. endJ)
- [x] Generalize variables and fields to a common interface. @chleh, (PR #1357)
- [x] Some cleanup of the Process class. I.e., move all information that is only forwarded to the time loop directly into the time loop. @chleh PR #1364.
- [x] Fix bug in GeoMapper @TomFischer PR #1368
- [x] Fix issue in Grid @TomFischer PR #1369
- [x] Time dependent BCs. #1380
- [x] Mechanics: Burgers material model (@endJunction) #1391 
## WIP
- [x] Mechanics: Surface yield function material model. (@endJunction & Xing)
- [x] Documentation of heat conduction process; Benchmark description. (@grubbymoon)
- [x] Liquid flow needed for weak TH coupling (@wenqing)
- [x] BCs output (to compute total fluxes in post-processing) @TomFischer https://github.com/TomFischer/ogs/tree/MeshElementOutput
- [x] Axial-symmetric problems (see issue #1310)
- [x] Being able to set BCs depending on the current state of the simulation, depends on time-dependent BCs. @chleh. @nagelt wants it, too, for switching between displacement and stress BCs
  - ~~Probably needs a cleanup of the output routines.~~
## Upcoming
- [x] Inhomogeneous BCs @TomFischer
- [ ] Time Stepping: PID  scheme (waiting for TH weak coupling) @norihiro-w 
- [ ] Add functionality to read new FEFLOW file format @TomFischer
- [x] Change data array name for calculating flux (issue #1449) @TomFischer
## Unordered
- [ ] From #1340 by Norihiro: "`MatrixTranslatorGeneral::computeResidual()` calculates residual as `r = M du/dt + K u - b`. This assembly is setting `b`. At the end, the residual becomes `r = inner force - external force` and the sign of the residual is consistent with the Jacobian. I don't think current approach is easy to understand and it should be improved in the future."
- [ ] It would be good to add make internal_pre_doc_qa_page to some of Jenkins' PR jobs in order to test the python and shell scripts? @endJunction. #1362  Linux-PRs maybe, or an extra job just for documentation, s.t. not to pollute the compilations.
- [ ] MaterialID based mesh properties; see [endJunction/ogs/MaterialIdBasedMeshProperties](https://github.com/endJunction/ogs/tree/MaterialIdBasedMeshProperties) branch. with examples!
- [x] Weak process coupling (depends on Parameters)
- [x] Fluid property classes for permeability, different models of density and viscosity
- [ ] Heat advection
- [ ] A non-overlapping domain output (parallel vtk)
- [ ] Mathematical expressions (muparser?) For special initial conditions. @chleh: muparser doesn't seem to support callable objects as custom functions, but exprtk does (example 5 on http://www.partow.net/programming/exprtk/).
- [x] MeshSubsets vs Element::active. Which one to keep, what are the problems being solved with this feature.
- [x] Setup of Rotenburg  model (33e6 cells, steady state groundwater flow) @TomFischer
- [ ] Setup a parallel version of Rotenburg model @TomFischer
- [x] Preparing tools for Hydro II tutorial @TomFischer
- [ ] Enabled compilation under Cygwin and fixed the compilation error under Apple #1324 (the PR has been closed for the time being)
- [ ] ...
## Backlog:

(4) Essential feature addition / deletion 
- [ ] Data output for each mesh, not for each process (I guess this influences the process interface)
- [ ] Global typedef for integer and real, e.g. `OgsInt`, `OgsReal`. This is necessary for supporting `long long` (e.g. more than 2 billion DoFs (e.g. 20 million HEX27 elements for mechanics in 3D) ) and quad precision, which are also supported by PETSc, Lis, and PARDISO.
- [ ] Introducing Parameters class (I am thinking something like TCLAP but parsing ConfigTree). This enables us to include documentation of parameters into the executable (and force developers to write short documentation for each parameter) so that we can print help of all parameters with `ogs --help-parameters`.

(5) Misc. feature addition / deletion
- [ ] add connectivity info to a DoF table. Currently we need to use both a mesh and a DoF table to get the information.
- [ ] OpenMP for assembly #1163
- [ ] Rework GEOObject, PointVec ... @TomFischer
- [ ] Minimize usage of template techniques for better developer friendly API and shorter compiling time (To be specified. Removing some templates is already given above. ) #1137
- [ ] Customize selection of libraries in cmake #1142
- [ ] rename NumLib/ODESolver to NumLib/TimeIntegration.
- [ ] clean up includes. @endJunction has some fancy tool for it. Maybe by that we already gain some compilation speed (at least if not building from scratch).
- [x] Pardiso linear solver (see issue #1175)
- [ ] Rename Process to MonolithicProcess
## Documentation
- [ ] Robin type boundary conditions @chleh 
- [ ] Benchmark description for TES and Robin bcs @chleh
- [x] Write prj file parameter documentation

**Comment by ogsbot** [comment]
OpenGeoSys development has been moved to [GitLab](https://gitlab.opengeosys.org/ogs/ogs).

[See this issue on GitLab](https://gitlab.opengeosys.org/ogs/ogs/-/issues/1350).
