### ISSUE TITLE
OGS-6 Milestones Overview

### ISSUE THREAD

**Issue by OlafKolditz** [ufz/ogs#363]
## By mathematical / computational functionality – Developer view

See progress for each milestone below this list.
### Linear problems
- [ ] **M1**: elliptic linear equations (steady-state problems), sequential version, homogeneous / heterogeneous materials (basic data structures for serial computations), @TomFischer, see #385  
- [ ] **M2**: elliptic linear equations, parallel version (basic data structures for parallel computations), subMs for specific parallel applications, @wenqing (#393)
- [ ] **M3**: parabolic linear equations (transient problems, e.g. groundwater flow, heat conduction, mass diffusion), tbd.
### Non-linear problems
- [ ] **M4:** non-linear problems: material properties (e.g. EoS, Richards flow, inelastic deformations), tbd.
- [ ] **M5:** non-linear problems: non-linear geometry (e.g. large deformations), @nagelt
### Coupled problems
- [ ] **M6:** volume coupling: partitioned (e.g. mass and heat transport), tbd.
- [ ] **M7:** volume coupling: monolithic (e.g. density-dependent flow), tbd.
- [ ] **M8:** volume coupling: mixed order (e.g. HM problems), @norihiro-w
- [ ] **M9:** code coupling (e.g. reactive mass transport, PHREEQC, GEM interfaces), @HaibingShao
- [ ] **M10:** boundary coupling (e.g. overland#Richards flow, OGS#mHM), tbd.
- [ ] **M11:** fully coupled problems (towards THMC), tbd.

**Comment by ogsbot** [comment]
OpenGeoSys development has been moved to [GitLab](https://gitlab.opengeosys.org/ogs/ogs).

[See this issue on GitLab](https://gitlab.opengeosys.org/ogs/ogs/-/issues/363).
